#!/bin/sh

DISPLAY=:0
export DISPLAY

primary="LVDS-1"
place="right"
rate="75"

wallpath="/home/brayan/Wallpapers/PC/"
wallname="wallhaven-2evglg_3840x2160.png"

monitors=$(xrandr | grep -En "[A-Z][A-Z][A-Z][A-Z]?-[1-9] connected" | cut -d ':' -f 2 | cut -d ' ' -f 1)
monitors=${monitors[@]/${primary}}
monitors_quantity=${#monitors[@]}

cache_dir="${HOME}/.config/monkey"
cache_file="monkey.txt"

[ ! -d $cache_dir ] && mkdir -p $cache_dir
[ ! -f ${cache_dir}/${cache_file} ] && touch ${cache_dir}/${cache_file}

reconfigure_wallpaper() {
        xwallpaper --stretch ${wallpath}/${wallname}
}

set_mode() {
        mode=$(head -n 1 /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-${i}/modes)
}

write_active_monitor() {
        echo $1 >> ${cache_dir}/${cache_file}
}

delete_deactived_monitor() {
        sed -i "s/$1//g" ${cache_dir}/${cache_file}
        local monitors=$(cat ${cache_dir}/${cache_file})
        rm ${cache_dir}/${cache_file}
        touch ${cache_dir}/${cache_file}
        for i in $monitors
        do
                echo $i >> ${cache_dir}/${cache_file}
        done
}

is_it_active() {
        local active_monitors=$(cat ${cache_dir}/${cache_file})
        for i in $active_monitors
        do
                if [ $i = $1 ]
                then
                        return 0
                fi
        done
        return 1
}

active_if_it_is_not() {
        is_it_active $1
        [ $? -eq 0 ] && return 1
        set_mode $1
        xrandr --output $primary --auto --primary --output $1 \
                --auto --mode $mode --${place}-of $primary --rate $rate
        write_active_monitor $1
        return 0
}

direct_deactive() {
        xrandr --output $1 --off
        reconfigure_wallpaper
        delete_deactived_monitor $1
}

check_if_it_has_been_disconnected() {
        local status=$(cat /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-${1}/status)
        [ $status = "disconnected" ] && return 0
        return 1
}

active() {
        for i in $monitors
        do
                active_if_it_is_not $i
                if [ $? -ne 0 ]
                then
                        check_if_it_has_been_disconnected $i
                        [ $? -eq 0 ] && direct_deactive $i && reconfigure_wallpaper
                else
                        reconfigure_wallpaper
                fi
        done
}

deactive() {
        local cached_monitors=$(wc -l < ${cache_dir}/${cache_file})
        for ((i=1; i<=$cached_monitors; ++i))
        do
                local monitor=$(head -n $i ${cache_dir}/${cache_file} | tail -n 1)
                [ -z $monitor ] && continue
                xrandr | grep $monitor > /dev/null
                if [ $? -ne 0 ]
                then
                        echo "Invalid monitor name, $monitor"
                        continue
                fi
                check_if_it_has_been_disconnected $monitor
                [ $? -eq 0 ] && direct_deactive $monitor && reconfigure_wallpaper
        done
}

if [[ -z ${monitors[@]} || $monitors_quantity -eq 0 ]]
then
        deactive
else
        active
fi
