#!/bin/sh

RED="\e[1;31m"
ORANGE="\e[1;33m"
RESET="\e[0m"
let IS_CONNECTED=0

function set_wallpaper {
        # Update wallpaper because of resolution's change ruin it.
        grep feh ${HOME}/.xinitrc | sh
}

function verify {
        if [ `xrandr | grep VGA | awk '{print $2;}'` == "connected" ]; then
                IS_CONNECTED=1
        fi
}

function on {
        verify
        if [ $IS_CONNECTED -ne 0 ]; then
                xrandr --output LVDS-1 --auto --primary --mode 1366x768 --rate 60 \
                        --output VGA-1 --auto --left-of LVDS-1 \
                        --mode 1280x1024 --rate 75
                set_wallpaper
        fi
}

function off {
        verify
        if [ $IS_CONNECTED -ne 0 ]; then
                xrandr --output VGA-1 --off
                set_wallpaper
        fi
}

function err {
        printf "$ORANGE%s $RED%s$RESET\n" "[on/off]" "what do you want to do?"
}

[ $# -eq 0 ] && err && exit 1
[ $1 == "on" ] && on && exit 0
[ $1 == "off" ] && off && exit 0

printf "${RED}%s $RESET" "Arguments:"
for i in $@; do
        printf "${ORANGE}${i}, "
done
printf "\b ${RED}%s${RESET}\n" "are not recognised."
