# -*- mode: sh; sh-basic-offset: 4; indent-tabs-mode: nil; -*-
#!/sbin/nft -f

destroy table inet vpn_killswitch

table inet vpn_killswitch {
    set physical_ifaces {
        type ifname
        elements = {
            "eno1",
            "wlan0"
        }
    }

    set wireguard_ifaces {
        type ifname
        elements = {
        }
    }

    set proton_endpoints_v4 {
        type ipv4_addr
        elements = {
        }
    }

    chain input {
        type filter hook input priority filter;
        policy drop;

        # Accept all incoming traffic on localhost.
        iifname "lo" accept

        # Drop non-classified conntrack.
        ct state invalid drop
        # Accept all incoming traffic we started.
        ct state established,related accept

        # DHCPv4.
        iifname @physical_ifaces \
                udp sport 67 udp dport 68 accept

        # DHCPv6.
        iifname @physical_ifaces \
                udp sport 547 udp dport 546 accept

        # Essential IPv6 ICMP errors.
        icmpv6 type {
            destination-unreachable,
            packet-too-big,
            time-exceeded,
            parameter-problem
        } accept

        # Neighbor Discovery / Router Advertisement.
        iifname @physical_ifaces icmpv6 type {
            nd-router-advert,
            nd-neighbor-solicit,
            nd-neighbor-advert
        } accept
    }

    chain forward {
        type filter hook forward priority filter;
        policy drop;
    }

    chain output {
        type filter hook output priority filter;
        policy drop;

        # Accept all outgoing traffic on localhost.
        oifname "lo" accept

        # Accept all outgoing traffic through WireGuard.
        oifname @wireguard_ifaces accept

        # Accept outgoing traffic through physical interfaces just to Proton endpoints.
        oifname @physical_ifaces \
                ip daddr @proton_endpoints_v4 \
                udp dport 51820 accept

        # DHCPv4.
        oifname @physical_ifaces \
                udp sport 68 udp dport 67 accept

        # DHCPv6.
        oifname @physical_ifaces \
                udp sport 546 udp dport 547 accept

        # IPv6 link control.
        oifname @physical_ifaces icmpv6 type {
            nd-router-solicit,
            nd-neighbor-solicit,
            nd-neighbor-advert
        } accept
    }
}
