#!/bin/sh
LOC=$(readlink -f "$0")
DIR=$(dirname "$LOC")
# Change the appearance of the module identifier. if this is set to "unicode",
# then symbols will be used as identifiers instead of text. E.g. [📪 0] instead of [MAIL 0].
# Requires a font with adequate unicode character support
export IDENTIFIER="unicode"

# Change the charachter(s) used to seperate modules. If two are used, they will be placed at the start and end.
export SEP1="["
export SEP2="]"

# Import modules
. "$DIR/utils/dwm_battery.sh"
. "$DIR/utils/dwm_alsa.sh"
. "$DIR/utils/dwm_keyboard.sh"
. "$DIR/utils/dwm_date.sh"
. "$DIR/utils/dwm_resources.sh"
. "$DIR/utils/dwm_acpilight.sh"
. "$DIR/utils/dwm_uptime.sh"

while true; do
        xsetroot -name "$(dwm_uptime)$(dwm_resources)$(dwm_acpilight)$(dwm_battery)$(dwm_alsa)$(dwm_keyboard)$(dwm_date)"
        sleep 1
done
