music_directory		"~/Music"
playlist_directory	"~/Music/Playlists"
db_file			"~/.config/mpd/database"
log_file		"~/.config/mpd/log"
state_file		"~/.config/mpd/state"
pid_file		"~/.config/mpd/pid"

bind_to_address		"~/.config/mpd/socket"
bind_to_address		"localhost"
port			"6650"

auto_update		"yes"
restore_paused		"yes"
log_level		"default"

audio_output {
    type "pipewire"
    name "Pipewire Output"
}
