# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Put your fun stuff here.

# Here start my personal configuration
# Colors: In there order: Red, GREEN, Blue, White and the final
colors=("\e[1;31m" "\e[1;32m" "\e[1;34m" "\e[1;37m" "\e[0m")
# Text in ASCII when start a new session.
message="| ￣￣￣￣￣￣|
| Los hackers |
| NO son |
| ciberdelincuentes |
| ＿＿＿＿＿＿＿＿ |
(__/) ||
(••) ||
/ 　 づ"
number=$(echo $(($RANDOM % 3)))
if [ $number -eq 0 ]; then
        echo -en "${colors[1]}"
        figlet "LORD BROOKIE"
        echo -en "${colors[4]}"
elif [ $number -eq 1 ]; then
        echo -en "${colors[2]}"
        cowsay "Hello, welcome again Lord Brookie!"
        echo -en "${colors[4]}"
else
        echo -e "${colors[3]}$message${colors[4]}"
fi

# Configuration of powerline.
if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . /usr/share/powerline/bash/powerline.sh
else
        echo -e "\n${colors[0]}Ha ocurrido un problema al encontrar el archivo de configuración de powerline.${colors[4]}\n"
fi

# Alias
alias p="ps aux | grep "
alias l="ls --color=auto -F"
alias la="ls -aF --color=auto"
alias ll="ls -lF --color=auto"
alias lla="ls -laF --color=auto"
alias lash="ls -ashF --color=auto"
alias music="youtube-dl -qx --audio-format mp3 $@ > /dev/null 2>&1"
alias video="youtube-dl -qf mp4 $@ > /dev/null 2>&1"

